version: 0.1.{build}

platform:
  - x64

cache:
#  - node_modules
#  - app\node_modules
#  - '%APPDATA%\npm-cache'
#  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - echo "Commit Message:"
  - echo %APPVEYOR_REPO_COMMIT_MESSAGE%
  - git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder@next # force install next version to test electron-builder
  - npm install
  - npm install --prefix ./client
  - npm run build --prefix ./client
  - npm prune

build_script:
  - node --version
  - npm --version
  - ps: >-
      If ($APPVEYOR_REPO_COMMIT_MESSAGE == *"release candidate"*) {
        npm run release
      } Else {
        npm run build
      }
  - npm run release

test: off